// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableRename;

#nullable disable

namespace TableRename.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211111223100_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TableRename.Entity1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Entity2Id")
                        .HasColumnType("int");

                    b.Property<int>("Entity3Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Entity2Id");

                    b.HasIndex("Entity3Id");

                    b.ToTable("Entity1s");
                });

            modelBuilder.Entity("TableRename.Entity2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Entity2s");
                });

            modelBuilder.Entity("TableRename.Entity3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Entity3s");
                });

            modelBuilder.Entity("TableRename.Entity1", b =>
                {
                    b.HasOne("TableRename.Entity2", "Entity2Navigation")
                        .WithMany("Entity1s")
                        .HasForeignKey("Entity2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableRename.Entity3", "Entity3Navigation")
                        .WithMany("Entity1s")
                        .HasForeignKey("Entity3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity2Navigation");

                    b.Navigation("Entity3Navigation");
                });

            modelBuilder.Entity("TableRename.Entity2", b =>
                {
                    b.Navigation("Entity1s");
                });

            modelBuilder.Entity("TableRename.Entity3", b =>
                {
                    b.Navigation("Entity1s");
                });
#pragma warning restore 612, 618
        }
    }
}
